name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Input Output Test
      id: input-output-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Input Output Test
        setup-command: ''
        command: python3 count_item/main.py
        input: |-
          a,b,c,a,b
          a
        expected-output: "^2$"
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUT-OUTPUT-TEST_RESULTS: "${{steps.input-output-test.outputs.result}}"
      with:
        runners: input-output-test
